### ISSUE TITLE
Firebase Auth and Steam Auth

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/Unity-MMORPG-KIT-Extensions-And-Plugins#1]
Just wanted to pitch these 3 custom addons I released recently.

https://github.com/GamerzDan/MMORPGKIT-Reset-Password-Addon
https://github.com/GamerzDan/MMORPGKIT-Firebase-AuthBackend
https://github.com/GamerzDan/MMORPGKIT-SteamAuth-Backend

**Comment by insthync** [comment]
Added, Thank you :)
